//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baiko_TestPlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingReports
    {
        public int test_id { get; set; }
        public Nullable<System.DateTime> test_date { get; set; }
        public string student_id { get; set; }
        public Nullable<int> bilet_id { get; set; }
        public Nullable<int> answer { get; set; }
        public Nullable<int> testing_time { get; set; }
        public Nullable<int> total_questions { get; set; }
        public Nullable<int> correct_answers { get; set; }
        public Nullable<int> student_grade { get; set; }
    
        public virtual Bilet Bilet { get; set; }
        public virtual Students Students { get; set; }
    }
}
